reduce differences between both scripts

diff --git a/deploy_toolchain_i686-ace-mingw32 b/deploy_toolchain_i686-ace-mingw32
--- a/deploy_toolchain_i686-ace-mingw32
+++ b/deploy_toolchain_i686-ace-mingw32
@@ -46,20 +46,18 @@ function main
   mkdir -p $ARCHIVES
   mkdir -p src bin
 
-  lazy binutils_download
+  binutils_download
+  gcc_download
+  gdc_download
+  mingw64_download
+
   lazy binutils_build
 
-  lazy mingw64_download
   lazy mingw64_extract
   lazy mingw64_install_headers
 
-  lazy gcc_download
   lazy gcc_extract
-  lazy gcc_patch
-
-  lazy gdc_download
   lazy gdc_apply
-
   lazy gcc_configure
   lazy gcc_standalone_build
   lazy gcc_standalone_install
@@ -111,7 +109,7 @@ MINGW64_BIN=bin/mingw64
 
 function mingw64_download
 {
-	wget "http://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v3.0.0.tar.bz2" -O "$ARCHIVES/mingw64.tar.bz2"
+	atomic_wget "http://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v3.0.0.tar.bz2" "$ARCHIVES/mingw64.tar.bz2"
 }
 
 function mingw64_extract
@@ -168,11 +166,6 @@ function gcc_extract
   popd
 }
 
-function gcc_patch
-{
-  patch -p1 --merge -d $GCC_SRC < $scriptDir/patches/gcc/0001-Remove-fPIC-for-MinGW.patch
-}
-
 function gcc_configure
 {
   local dir=../../$GCC_SRC # 'dir' must be a relative path, otherwise GMP will not build under Msy2/Cygwin
@@ -225,17 +218,19 @@ function gcc_install
 #------------------------------------------------------------------------------
 function gdc_download
 {
-  rm -rf src/gdc
+  if [ -d src/gdc ] ; then
+    echo "Already downloaded: gdc"
+    return 0;
+  fi
   git clone https://github.com/D-Programming-GDC/GDC.git src/gdc
-  pushd src/gdc
-  git checkout origin/gdc-5
-  git checkout $GDC_COMMIT
-  popd
 }
 
 function gdc_apply
 {
+  patch -p1 --merge -d $GCC_SRC < $scriptDir/patches/gcc/0001-Remove-fPIC-for-MinGW.patch
 	pushd src/gdc
+  git checkout origin/gdc-5
+  git checkout $GDC_COMMIT
   ./setup-gcc.sh ../gcc
   popd
 }
@@ -277,7 +272,10 @@ function lazy
   echo "$func ..."
   $func & # fork: prevent the callee to change the caller's environment
   pid=$!
-  wait $pid
+  if ! wait $pid ; then
+    echo "Failure with: $func"
+    return 1
+  fi
 
   mkdir -p $BIN/flags
   touch $BIN/flags/$func
